import axios from 'axios'

export default async function createPlaylist(
   sliderValues,
   settings,
   setIsLoading,
   selectedSliders,
   token
) {
   let requestURL = 'http://127.0.0.1:5001/recommend_tracks/?'
   for (let index = 1; index < sliderValues.length; index++) {
      const { step, key } = settings[index]
      requestURL += selectedSliders.includes(key)
         ? `${key}=${
              step
                 ? sliderValues[index]
                 : ((1.0 * sliderValues[index]) / 100).toFixed(3)
           }&`
         : ''
   }
   requestURL += `${settings[0].key[0]}=${sliderValues[0][0]}&${settings[0].key[1]}=${sliderValues[0][1]}`
   let { res: tracks } = await fetch(requestURL)
      .then((res) => {
         setIsLoading(false)
         return res.json()
      })
      .catch((err) => console.error(err))

   const user = await axios.get('https://api.spotify.com/v1/me/', {
      headers: {
         Accept: 'application/json',
         Authorization: `Bearer ${token}`,
         'Content-Type': 'application/json',
      },
   })

   const playlist = await axios.get(
      `https://api.spotify.com/v1/users/${user_id}/playlists`,
      {
         headers: {
            Accept: 'application/json',
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json',
         },
         params: {
            name: `SpotAI Playlist ${Math.round(Math.random() * 1000000000)} `,
            public: false,
            description: 'A playlist generated by SpotAI',
         },
      }
   )
   console.log(user)
   console.log(playlist)

   let uris = ''
   tracks.forEach((id) => {
      uris += `spotify:track:${id},`
   })
   uris = uris.slice(0, -1)

   await await axios.get(
      `https://api.spotify.com/v1/playlists/${pl_id}/tracks`,
      {
         headers: {
            Accept: 'application/json',
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json',
         },
         params: {
            uris: uris,
         },
      }
   )

   const { data } = await axios.get('https://api.spotify.com/v1/me/playlists', {
      headers: {
         Accept: 'application/json',
         Authorization: `Bearer ${token}`,
         'Content-Type': 'application/json',
      },
      params: { limit: 50, offset: 0 },
   })
   setPlaylists({ data }.data.items)
}
